#!/bin/bash
# 显示 Clash Web 面板访问信息

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "=========================================="
echo "Clash Web 面板访问信息"
echo "=========================================="
echo ""
echo "面板地址: http://localhost:9090/ui"
echo ""
echo "首次打开面板需要手动连接后端："
echo "  点击「切换后端」或齿轮图标，填入以下信息："
echo ""
echo "  API Base URL:"
echo "    - WSL 环境:    http://localhost:9090"
echo "    - 远程服务器:  http://<服务器公网IP>:9090"
echo ""
echo "  Secret: MySuperSecret123"
echo ""
echo "  （Yacd 面板是在你浏览器里运行的前端应用，"
echo "    所以 WSL 填 localhost 即可，"
echo "    服务器必须填公网 IP，填 localhost 会指向你自己的电脑）"
echo ""
echo "=========================================="
echo "Quick commands:"
echo "  Status: bash $SCRIPT_DIR/clash-status.sh"
echo "  Stop:   bash $SCRIPT_DIR/clash-stop.sh"
echo "=========================================="
